#pragma once

#pragma pack(1)
typedef struct _DESCRIPTOR {
	UINT16 limit;
	UINT64 addr;
} DESCRIPTOR, *PDESCRIPTOR;

typedef struct _CPU_INFO {
	DESCRIPTOR Idtr;
	DESCRIPTOR Gdtr;
} CPU_INFO, * PCCPU_INFO;
#pragma pack()

#define CPU_INFO_ sizeof(CPU_INFO)

#define IOCTL_TESTDRV CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_CPU_INFO CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

